"""
core/config.py
Buildway Tech (HK) Limited — Configuration & Secrets Management
Supports both .env (local dev) and Streamlit secrets (cloud deployment)
"""

import os
from pathlib import Path

# Try to load .env for local development
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Try to load Streamlit secrets (cloud deployment)
def _get_secret(key: str, default: str = "") -> str:
    """Retrieve a secret from Streamlit secrets or environment variables."""
    # Try Streamlit secrets first (cloud)
    try:
        import streamlit as st
        if hasattr(st, "secrets") and key in st.secrets:
            return st.secrets[key]
    except Exception:
        pass
    # Fall back to environment variable
    return os.getenv(key, default)


# ─── App Identity ────────────────────────────────────────────────────────────
APP_NAME = "Buildway Tech (HK) Limited"
APP_SUBTITLE = "香港股票智能分析系統 — Landing + Report Summary Cleanup Layer"
APP_VERSION = "v0.7.0"
BUILD_STAGE = "Report History + Watchlist Layer"
APP_LANG = "zh-HK"

# ─── Deployment Environment Detection ────────────────────────────────────────
def _detect_environment() -> str:
    """Detect whether running on Streamlit Cloud or local."""
    # Streamlit Cloud sets STREAMLIT_SERVER_HEADLESS=true and specific env vars
    if os.environ.get("STREAMLIT_SERVER_HEADLESS") == "true":
        return "streamlit-cloud"
    if os.environ.get("HOME", "").startswith("/home/") and not os.environ.get("COMPUTERNAME"):
        return "streamlit-cloud"
    return "local"

DEPLOY_ENV = _detect_environment()

# ─── Build Version (auto-resolved from git, falls back to static) ─────────────
def _get_git_commit() -> str:
    """Return short git commit hash for version display."""
    try:
        import subprocess
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=3,
            cwd=str(Path(__file__).resolve().parent.parent),
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "unknown"

BUILD_COMMIT = _get_git_commit()
BUILD_VERSION = f"{APP_VERSION} ({BUILD_COMMIT})"

# ─── Asset Paths ─────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent
ASSETS_DIR = BASE_DIR / "assets"
REPORTS_DIR = BASE_DIR / "reports"
LOGO_PATH = ASSETS_DIR / "logo.png"

# Ensure reports directory exists
REPORTS_DIR.mkdir(exist_ok=True)

# ─── API Keys (never hardcoded) ───────────────────────────────────────────────
OPENAI_API_KEY = _get_secret("OPENAI_API_KEY")
ALPHA_VANTAGE_KEY = _get_secret("ALPHA_VANTAGE_KEY")
FINNHUB_API_KEY = _get_secret("FINNHUB_API_KEY")
NEWS_API_KEY = _get_secret("NEWS_API_KEY")

# ─── Feature Flags ────────────────────────────────────────────────────────────
USE_LIVE_MARKET_DATA = _get_secret("USE_LIVE_MARKET_DATA", "false").lower() == "true"
USE_AI_ANALYSIS = _get_secret("USE_AI_ANALYSIS", "false").lower() == "true"
DEV_MODE = True  # This is the DEV trial app

# ─── Report Settings ──────────────────────────────────────────────────────────
PDF_FONT = "NotoSansCJK"          # CJK-compatible font
PDF_PAGE_SIZE = "A4"
REPORT_AUTHOR = "Buildway Tech (HK) Limited — AI Analysis System"

# ─── Risk Score Thresholds ────────────────────────────────────────────────────
RISK_LEVELS = {
    "低風險":   (1, 3),
    "中等風險": (4, 6),
    "高風險":   (7, 8),
    "極高風險": (9, 10),
}

# ─── Investment Committee Verdicts ───────────────────────────────────────────
IC_VERDICTS = ["觀察名單", "高風險", "中性", "正面", "避免"]

# ─── Disclaimer Text ─────────────────────────────────────────────────────────
DISCLAIMER_ZH = """
【重要免責聲明】

本報告由 Buildway Tech (HK) Limited AI 分析系統生成，僅供教育及參考用途，
不構成任何投資建議、買賣邀請或財務意見。

本系統為 DEV 試用版本，所有數據可能包含模擬或示範數據，並非實時市場數據。
投資涉及風險，股票價格可升可跌，投資者可能損失全部投資。

在作出任何投資決定前，請諮詢持牌財務顧問。
本報告不應被視為香港《證券及期貨條例》下的受規管活動。

© 2025 Buildway Tech (HK) Limited. 版權所有。
"""

DISCLAIMER_EN = """
IMPORTANT DISCLAIMER

This report is generated by Buildway Tech (HK) Limited AI Analysis System for 
educational and informational purposes only. It does not constitute investment 
advice, an offer to buy or sell, or financial guidance of any kind.

This is a DEV trial version. All data may include simulated or demo data and 
does not represent real-time market information. Investments involve risk; 
stock prices can go up or down, and investors may lose their entire investment.

Please consult a licensed financial advisor before making any investment decisions.
This report should not be regarded as a regulated activity under the 
Securities and Futures Ordinance (Cap. 571) of Hong Kong.

© 2025 Buildway Tech (HK) Limited. All rights reserved.
"""
